name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
    
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install -r requirements.txt

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: fxg1337/XIF_reader@main

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: XIF_reader/
